[theme]
primaryColor = "#4A90E2"                  # Azul moderno e suave para botões
backgroundColor = "#F3F6FA"               # Fundo geral claro com leve azul
secondaryBackgroundColor = "#E9F1FB"      # Fundo de elementos (cards, filtros)
textColor = "#0A0A0A"                      # Preto suave para legibilidade
font = "sans serif"                        # Fonte moderna e limpa